# Site settings
project: xhamster
baseurl: /xHamster.bundle
email: manferwebs@gmail.com
github_username: manfer
bootstrap_theme: slate

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [with_toc_data]

